import LateralMenu from "@/components/LateralMenu";
import "./globals.css";
import { Inter } from "next/font/google";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "To Do App | NextJS + MongoDB",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="es">
      <body className={`flex h-screen ${inter.className}`}>
        <LateralMenu />
        <main className="container flex-1 mt-4">{children}</main>
      </body>
    </html>
  );
}
